### ISSUE TITLE
Create Initial Stylescape Concept for Visual Identity

### ISSUE THREAD

**Issue by Blatantness** [devkdo/dotant#9]
Acceptance Criteria: 2-3 concepts of visual design.

**Comment by devkdo** [comment]
Gathered content for presentation. Next steps- organize/put together.

**Comment by devkdo** [comment]
Fine-tuning individual boards. Waiting to present at branding call on Friday

**Comment by devkdo** [comment]
Waiting for Friday brand call.

**Comment by devkdo** [comment]
2/17 completed branding call @Blatantness

**Comment by devkdo** [comment]
@Blatantness :
This week/ next sprint: #10 #11 
- looking at logos and wireframes
- beef up list of screen layouts
    - make wireframes for them
    - collect collateral
